version: "3.8"
services:
  backend:
    build: ./backend
    container_name: wppconnect-backend
    ports:
      - "3002:3002"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: wppconnect-frontend
    ports:
      - "3010:80"
    restart: unless-stopped
