version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: wppconnect-backend
    ports:
      - "3002:3002"
    environment:
      - PUPPETEER_CHROMIUM_ARGS=--no-sandbox
      - GENERIC_TIMEZONE=Asia/Kolkata
      - TZ=Asia/Kolkata 
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: wppconnect-frontend
    ports:
      - "3010:80"
    restart: unless-stopped
